### ISSUE TITLE
Added a ton of feeds and it does not upload any more

### ISSUE THREAD

**Issue by Dr1nS0menOp** [cudeso/misp2sentinel#118]
script.py gets stuck at a certain event even if I delete it. It worked before but when I added a lot of feeds it got stuck processing all indicators. Is this just me being inpatient or is it in a error?
![image](https://github.com/user-attachments/assets/c29fc1e9-8efc-4469-94fa-0bd3d90d1dad)

It normally continues but it has been stuck on this last line for an hour.

I execute the the script with:
`/home/adminsng/misp2sentinel/ ; /home/adminsng/misp2sentinel/sentinel/bin/python /home/adminsng/misp2sentinel/script.py
`
And view the logs with: 
`tail -f /tmp/misp2sentinel.log`

**Comment by Dr1nS0menOp** [comment]
Now I removed almost all feeds and deleted the Events and it is still broken. Worked perfect for weeks!
Do't know how this is happening.

**Comment by Dr1nS0menOp** [comment]
OK issue got solved. The script is just really vague and it continued after 10 minutes when I removed a lot of events. So it can be mentioned that a lof of feeds severly slow down the upload process to a point that you think it is stuck.

**Comment by Dr1nS0menOp** [comment]
Closed

**Comment by cudeso** [comment]
Because Sentinel expects STIX, the synchronisation script transforms the MISP events to STIX data, this requires some memory resources. Maybe your system ran out of available memory? Check for Linux OOM messages.
You can limit the amount of events ('batches') it loads into memory with `misp_event_limit_per_page`. Lowering the value limits the memory usage.
